apps/companies/urls.py
from django.conf.urls import patterns, url
from .views import (
    CompanyListView,
    CompanyDetailView,
    company_sidebar,
    create_company,
    manage_company,
    UpdateBusinessSegmentsView,
    UpdateScopeOfOperationView,
    UpdateCompanyLogoView,
    UpdateCompanyDescriptionView,
    UpdateCompanyAddressesView,
    UpdateCompanyContactsView,
    manage_company_staff,
    manage_company_equipment,
    manage_company_equipment_category,
    manage_company_add_equipment,
)

urlpatterns = patterns(
    '',
    url(r'^companies/$', CompanyListView.as_view(), name='company_list'),
    url(r'^companies/add/$', create_company, name='company_add'),
    url(
        r'^companies/(?P<slug>[-\w]+)/$', CompanyDetailView.as_view(),
        name='company_details'),
    url(
        r'^companies/(?P<slug>[-\w]+)/sidebar/$', company_sidebar,
        name='company_sidebar'),

    url(
        r'^companies/(?P<slug>[-\w]+)/manage/$', manage_company,
        name='company_manage'),
    url(
        r'^companies/(?P<slug>[-\w]+)/manage/edit-business-segments/$',
        UpdateBusinessSegmentsView.as_view(),
        name='company_edit_business_segments'),
    url(
        r'^companies/(?P<slug>[-\w]+)/manage/edit-scope-of-operation/$',
        UpdateScopeOfOperationView.as_view(),
        name='company_edit_scope_of_operation'),
    url(
        r'^companies/(?P<slug>[-\w]+)/manage/edit-logo/$',
        UpdateCompanyLogoView.as_view(),
        name='company_edit_logo'),
    url(
        r'^companies/(?P<slug>[-\w]+)/manage/description/$',
        UpdateCompanyDescriptionView.as_view(),
        name='company_manage_description'),
    url(
        r'^companies/(?P<slug>[-\w]+)/manage/addresses/$',
        UpdateCompanyAddressesView.as_view(),
        name='company_manage_addresses'),
    url(
        r'^companies/(?P<slug>[-\w]+)/manage/contacts/$',
        UpdateCompanyContactsView.as_view(),
        name='company_manage_contacts'),
    url(
        r'^companies/(?P<slug>[-\w]+)/manage/staff/$',
        manage_company_staff,
        name='company_manage_staff'),
    url(
        r'^companies/(?P<slug>[-\w]+)/manage/equipment/$',
        manage_company_equipment,
        name='company_manage_equipment'),
    url(
        r'^companies/(?P<slug>[-\w]+)/manage/'
        'equipment/(?P<category_slug>[-\w]+)/$',
        manage_company_equipment_category,
        name='company_manage_equipment_category'),

    url(
        r'^companies/(?P<slug>[-\w]+)/manage/'
        'equipment/(?P<category_slug>[-\w]+)/add-equipment/$',
        manage_company_add_equipment,
        name='company_manage_add_equipment'),
)

apps/equipment/urls.py
from django.conf.urls import patterns, url
import mptt_urls
from .views import (
    # ManufacturerListView,
    # ManufacturerDetailView,
    equipment_search_view,
    # category_view,
    equipment_view,
    # equipment_item_view,
)

urlpatterns = patterns(
    '',
    # url(
    #     r'^manufacturers/$',
    #     ManufacturerListView.as_view(),
    #     name='manufacturer_list'),
    # url(
    #     r'^manufacturers/(?P<slug>[-\w]+)/$',
    #     ManufacturerDetailView.as_view(),
    #     name='manufacturer_details'),
    # url(
    #     r'^equipment/(?P<manufacturer_slug>[-\w]+)/(?P<slug>[-\w]+)/(?P<id>\d+)/$',
    #     equipment_item_view,
    #     name='equipment_item_details'),
    url(
        r'^equipment/(?P<category_slug>[-\w]+)/(?P<manufacturer_slug>[-\w\d]+)/(?P<model>[-\w\d]+)/(?P<id>\d+)/$',
        equipment_view,
        name='equipment_details'),
    # url(
    #     r'^categories/(?P<path>[-\w/]*)/$',
    #     mptt_urls.view(
    #         model='apps.equipment.models.EquipmentCategory',
    #         view=category_view,
    #         slug_field='slug'),
    #     name='category_details'),
    # url(
    #     r'^categories/(?P<slug>[-\w]+)/$',
    #     EquipmentCategoryDetailView.as_view(),
    #     name='category_details'),
    url(r'^search/$', equipment_search_view, name='search'),
)

apps/invitation/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required
from .settings import INVITE_ONLY


urlpatterns = patterns(
    '',
    url(r'^invitation/$',
        login_required(TemplateView.as_view(
            template_name='invitation/invitation_home.html')),
        name='invitation_home'),
    url(r'^invitation/invite/$',
        'apps.invitation.views.invite',
        name='invitation_invite'),
    url(r'^invitation/invite/complete/$',
        login_required(TemplateView.as_view(
            template_name='invitation/invitation_complete.html')),
        name='invitation_complete'),
    url(r'^invitation/invite/unavailable/$',
        login_required(TemplateView.as_view(
            template_name='invitation/invitation_unavailable.html')),
        name='invitation_unavailable'),
    url(r'^invitation/accept/complete/$',
        TemplateView.as_view(
            template_name='invitation/invitation_registered.html'),
        name='invitation_registered'),
    url(r'^invitation/accept/(?P<invitation_key>\w+)/$',
        'apps.invitation.views.register',
        name='invitation_register'),
)


if INVITE_ONLY:
    urlpatterns += patterns(
        '',
        url(r'^register/$',
            RedirectView.as_view(
                url='../invitation/invite_only/',
                permanent=False),
            name='registration_register'),
        url(r'^invitation/invite_only/$',
            TemplateView.as_view(
                template_name='invitation/invite_only.html'),
            name='invitation_invite_only'),
        url(r'^invitation/reward/$',
            'apps.invitation.views.reward',
            name='invitation_reward'),
    )

cranelocator/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = patterns(
    '',
    url(r'^$', 'cranelocator.views.home', name='home'),

    url(r'^', include('apps.accounts.urls')),
    url(r'^', include('apps.invitation.urls')),
    url(r'^', include('apps.companies.urls')),
    url(r'^', include('apps.equipment.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),

    url('^robots\.txt$', TemplateView.as_view(
        template_name='robots.txt', content_type='text/plain')),
    url('^humans\.txt$', TemplateView.as_view(
        template_name='humans.txt', content_type='text/plain')),
)


# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/companies/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from sorl.thumbnail import ImageField
from ckeditor.fields import RichTextField
from django_countries.fields import CountryField


# Validators


def validate_company_name(value):
    try:
        Company.objects.get(name__exact=value)
        raise ValidationError(_('Company with such name already exists.'))
    except Company.DoesNotExist:
        return value


def validate_vat(value):
    try:
        Company.objects.get(vat__exact=value)
        raise ValidationError(
            _('Company with such VAT number already exists.'))
    except Company.DoesNotExist:
        return value
    except Company.MultipleObjectsReturned:
        raise ValidationError(_(
            'Multiple companies with the same VAT number are in DB. '
            'Use your database management tool for fix that.'
        ))

# Models


class BusinessSegment(models.Model):
    label = models.CharField(_('Label'), max_length=100)
    code = models.SlugField(_('Code'))

    class Meta:
        verbose_name = _('Business segment')
        verbose_name_plural = _('Business segments')
        ordering = ('label',)

    def __str__(self):
        return self.label


class ScopeOfOperation(models.Model):
    label = models.CharField(_('Label'), max_length=100)
    code = models.SlugField(_('Code'))

    class Meta:
        verbose_name = _('Scope of operation')
        verbose_name_plural = _('Scopes of operation')
        ordering = ('label',)

    def __str__(self):
        return self.label


class Company(models.Model):
    name = models.CharField(_('Name'), max_length=100)
    slug = models.SlugField(_('Slug'))
    logo = ImageField(
        _('Logo'), upload_to='companies/logos', blank=True, null=True)
    vat = models.CharField(_('VAT Number'), max_length=100)

    # Description
    short_description = RichTextField(
        _('Short description'), config_name='basic', blank=True, default='')
    description = RichTextField(
        _('Description'), config_name='basic', blank=True, default='')

    # Visit address
    visit_street = models.CharField(
        _('Street'), max_length=255, default='', blank=True)
    visit_house_number = models.CharField(
        _('House number'), max_length=50, default='', blank=True)
    visit_additional_info = models.TextField(
        _('Additional info'), blank=True, default='')
    visit_post_code = models.CharField(
        _('Post code'), max_length=50, default='', blank=True)
    visit_city = models.CharField(
        _('City'), max_length=255, default='', blank=True)
    visit_country = CountryField(_('Country'))

    # Invoice address
    invoice_street = models.CharField(
        _('Street'), max_length=255, default='', blank=True)
    invoice_house_number = models.CharField(
        _('House number'), max_length=50, default='', blank=True)
    invoice_additional_info = models.TextField(
        _('Additional info'), blank=True, default='')
    invoice_post_code = models.CharField(
        _('Post code'), max_length=50, default='', blank=True)
    invoice_city = models.CharField(
        _('City'), max_length=255)
    invoice_country = CountryField(_('Country'))

    # Company contacts
    pnone1 = models.CharField(
        _('First phone'), max_length=50, default='', blank=True,
        help_text=_('Phone number including international code.'))
    pnone2 = models.CharField(
        _('Second phone'), max_length=50, default='', blank=True,
        help_text=_('Phone number including international code.'))
    fax = models.CharField(
        _('Fax'), max_length=50, default='', blank=True,
        help_text=_('Fax number including international code.'))
    email = models.EmailField(
        _('Email'), blank=True, default='')
    web_site = models.URLField(
        _('Web site'), blank=True, default='')

    # Contact persons
    cp1_name = models.CharField(
        _('Full name'), max_length=100, default='', blank=True)
    cp1_position = models.CharField(
        _('Position'), max_length=100, default='', blank=True)
    cp1_phone = models.CharField(
        _('Phone'), max_length=100, default='', blank=True,
        help_text=_('Phone number including international code.'))
    cp1_email = models.EmailField(
        _('Email'), blank=True, default='')
    cp1_skype = models.CharField(
        _('Skype'), max_length=50, default='', blank=True)

    cp2_name = models.CharField(
        _('Full name'), max_length=100, default='', blank=True)
    cp2_position = models.CharField(
        _('Position'), max_length=100, default='', blank=True)
    cp2_phone = models.CharField(
        _('Phone'), max_length=100, default='', blank=True,
        help_text=_('Phone number including international code.'))
    cp2_email = models.EmailField(
        _('Email'), blank=True, default='')
    cp2_skype = models.CharField(
        _('Skype'), max_length=50, default='', blank=True)

    # Depots and employees
    depots = models.IntegerField(_('Depots'), default=0)
    employees = models.IntegerField(_('Employees'), default=0)

    # SEO
    meta_title = models.CharField(
        _('META title'), blank=True, max_length=250,
        default='{{site_name}} - {{company.name}}')
    meta_description = models.TextField(
        _('META description'), blank=True,
        default='{{company.name}}')

    business_segments = models.ManyToManyField(
        BusinessSegment, verbose_name=_('Business segments'),
        null=True, blank=True)
    scope_of_operation = models.ManyToManyField(
        ScopeOfOperation, verbose_name=_('Scope of region operation'),
        null=True, blank=True)

    added = models.DateTimeField(_('Added'), auto_now_add=True)
    last_change = models.DateTimeField(_('Last change'), auto_now=True)

    verified = models.BooleanField(_('Verified'), default=False, blank=True)

    class Meta:
        verbose_name = _('Company')
        verbose_name_plural = _('Companies')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse(
            'company_details',
            kwargs={'slug': self.slug})

    def get_roles(self):
        return self.roles.all()

    def get_visit_address_string(self):
        _t = [
            self.visit_post_code,
            self.visit_city,
            self.get_visit_country_display(),
            self.visit_street,
            self.visit_house_number,
            self.visit_additional_info,
        ]
        return ', '.join([i for i in _t if i])

    def get_invoice_address_string(self):
        _t = [
            self.invoice_post_code,
            self.invoice_city,
            self.get_invoice_country_display(),
            self.invoice_street,
            self.invoice_house_number,
            self.invoice_additional_info,
        ]
        return ', '.join([i for i in _t if i])

    def get_categories(self):
        _cs = [bs.label for bs in self.business_segments.all()]
        if _cs:
            return ' | '.join(_cs)
        else:
            return ''

    def get_scope_of_operation(self):
        _ss = [so.label for so in self.scope_of_operation.all()]
        if _ss:
            return ' | '.join(_ss)
        else:
            return ''

    def _get_meta_data(self):
        data = {
            'company': self,
            'site_name': settings.PROJECT_NAME,
        }
        return data

    def _render_meta(self, text):
        from django.template import Context, Template
        context = Context(self._get_meta_data())
        template = Template(text)
        return template.render(context)

    def get_meta_title(self):
        return self._render_meta(self.meta_title)

    def get_meta_description(self):
        return self._render_meta(self.meta_description)


class CompanyUserRole(models.Model):
    COMPANY_ROLE_CHOICES = (
        ('owner', _('Owner')),
        ('manager', _('Manager')),
    )

    company = models.ForeignKey(
        Company, verbose_name=_('Company'),
        related_name='roles')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_('User'),
        related_name='company_roles')
    role = models.CharField(
        _('Role'), max_length=20, choices=COMPANY_ROLE_CHOICES)

    class Meta:
        verbose_name = _('Company user role')
        verbose_name_plural = _('Company user roles')

    def __str__(self):
        return '%s - %s' % (self.user, self.company)

apps/companies/templates/companies/_category_list.html
{% load i18n staticfiles %}
<div class="row">
{% for c in categories %}
<div class="col-xs-6 col-md-4">
    <div class="thumbnail" style="height:200px;">
      {% if c.icon %}
      <img src="{{ c.icon.url }}" alt="{{ c.name }}">
      {% else %}
      <img src="{% static 'img/placeholder-100x100.png' %}" alt="{{ c.name }}">
      {% endif %}
      <div class="caption">
        <h4 style="text-align:center;">
        <a href="{% url 'company_manage_equipment_category' company.slug c.slug %}">{{ c.name }}</a></h4>
        {% if c.equipment_amount %}
        <p style="text-align:center;"><small>{% trans "Equipment" %}: {{ c.equipment_amount }}</small></p>
        {% endif %}
      </div>
    </div>
</div>
{% endfor %}
</div>

apps/companies/templates/companies/_company_roles_for_company.html
{% load i18n %}
{% with company.get_roles as roles %}
{% if roles %}
<h4>{% trans "People in this company" %}</h4>
<table class="table table-hover table-bordered">
{% for role in roles %}
<tr>
    <td>{{ role.user }}</td>
    <td>{{ role.get_role_display }}</td>
</tr>
{% endfor %}
</table>
{% endif %}
{% endwith %}

apps/companies/templates/companies/_company_sidebar.html
{% load i18n staticfiles %}
{% if user.is_authenticated %}

<table class="table">
<tr>
    <td>{% trans "Company contacts" %}</td>
    <td>
        {% if company.pnone1 %}<span class="glyphicon glyphicon-earphone" aria-hidden="true" title="{% trans 'Phone 1' %}"></span>
        {{ company.pnone1 }}<br>{% endif %}
        {% if company.pnone2 %}<span class="glyphicon glyphicon-earphone" aria-hidden="true" title="{% trans 'Phone 2' %}"></span>
        {{ company.pnone2 }}<br>{% endif %}
        {% if company.fax %}<span class="glyphicon glyphicon-phone-alt" aria-hidden="true" title="{% trans 'Fax' %}"></span>
        {{ company.fax }}<br>{% endif %}
        {% if company.email %}<span class="glyphicon glyphicon-envelope" aria-hidden="true" title="{% trans 'Email' %}"></span>
        <a href="mailto:{{ company.email }}">{{ company.email }}</a><br>{% endif %}
        {% if company.web_site %}<span class="glyphicon glyphicon-link" aria-hidden="true" title="{% trans 'Web site' %}"></span>
        <a href="{{ company.web_site }}" rel="nofollow">{{ company.web_site }}</a>{% endif %}
    </td>
</tr>
<tr>
    <td width="40%">{% trans "Visit address" %}:</td>
    <td>{{ company.get_visit_address_string }}</td>
</tr>
<tr>
    <td>{% trans "Invoice address" %}:</td>
    <td>{{ company.get_invoice_address_string }}</td>
</tr>
{% if company.cp1_name or company.cp2_name %}
<tr>
    <td colspan="2">{% trans "Contact persons" %}</td>
</tr>
{% if company.cp1_name %}
<tr>
    <td>{{ company.cp1_name }}{% if company.cp1_position %}, {{ company.cp1_position }}{% endif %}</td>
    <td>
        {% if company.cp1_phone %}<span class="glyphicon glyphicon-earphone" aria-hidden="true" title="{% trans 'Phone' %}"></span>
        {{ company.cp1_phone }}<br>{% endif %}
        {% if company.cp1_email %}<span class="glyphicon glyphicon-envelope" aria-hidden="true" title="{% trans 'Email' %}"></span>
        {{ company.cp1_email }}<br>{% endif %}
        {% if company.cp1_skype %}<i class="fa fa-skype" aria-hidden="true" title="{% trans 'Skype' %}"></i>
        {{ company.cp1_skype }}{% endif %}
    </td>
</tr>
{% endif %}
{% if company.cp2_name %}
<tr>
    <td>{{ company.cp2_name }}{% if company.cp1_position %}, {{ company.cp2_position }}{% endif %}</td>
    <td>
        {% if company.cp2_phone %}<span class="glyphicon glyphicon-earphone" aria-hidden="true" title="{% trans 'Phone' %}"></span>
        {{ company.cp2_phone }}<br>{% endif %}
        {% if company.cp2_email %}<span class="glyphicon glyphicon-envelope" aria-hidden="true" title="{% trans 'Email' %}"></span>
        {{ company.cp2_email }}<br>{% endif %}
        {% if company.cp2_skype %}<i class="fa fa-skype" aria-hidden="true" title="{% trans 'Skype' %}"></i>
        {{ company.cp2_skype }}{% endif %}
    </td>
</tr>
{% endif %}
{% endif %}
</table>

{% if can_manage %}
<hr>
<a class="btn btn-warning btn-block" href="{% url 'company_manage' company.slug %}">
<small><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>  {% trans "Manage company" %}</a>
{% endif %}
{% else %}
<div class="alert alert-info">
{% trans "Only registered users may read additional information about companies." %}
</div>
<p><a class="btn btn-default" href="{% url 'login' %}?next={{ company.get_absolute_url }}">{% trans "Login" %}</a></p>
{% endif %}

apps/companies/templates/companies/_side_toolbar.html
{% load i18n %}
<div class="list-group">
    <a href="{% url 'company_manage' company.slug %}" class="list-group-item{% if section == 'summary' %} active{% endif %}">{% trans "Summary" %}</a>
    <a href="{% url 'company_manage_description' company.slug %}" class="list-group-item{% if section == 'description' %} active{% endif %}">{% trans "Description" %}</a>
    <a href="{% url 'company_manage_addresses' company.slug %}" class="list-group-item{% if section == 'addresses' %} active{% endif %}">{% trans "Addresses" %}</a>
    <a href="{% url 'company_manage_contacts' company.slug %}" class="list-group-item{% if section == 'contacts' %} active{% endif %}">{% trans "Contacts" %}</a>
    <a href="{% url 'company_manage_staff' company.slug %}" class="list-group-item{% if section == 'staff' %} active{% endif %}">{% trans "Staff" %}</a>
    <a href="{% url 'company_manage_equipment' company.slug %}" class="list-group-item{% if section == 'equipment' %} active{% endif %}">{% trans "Equipment" %}</a>
    {#<a href="#" class="list-group-item">{% trans "Messages" %}</a>#}
</div>

apps/companies/templates/companies/company_add.html
{% extends "base.html" %}
{% load i18n staticfiles thumbnail crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Create company" %}{% endblock %}

{% block head_tail %}{{ form.media }}{% endblock %}

{% block breadcrumb_path %}{{ block.super }}
<li><a href="{% url 'company_list' %}">{% trans "Companies" %}</a></li>
<li class="active">{% trans "Create company" %}</li>{% endblock %}

{% block content %}
<h2>{% trans "Create company" %}</h2>

{% crispy form %}

{% endblock %}

apps/companies/templates/companies/company_detail.html
{% extends "base.html" %}
{% load i18n staticfiles thumbnail %}

{% block title %}{{ company.get_meta_title }}{% endblock %}

{% block meta %}
    <meta name="description" content="{{ company.get_meta_description }}" />
{% endblock %}

{% block breadcrumb_path %}{{ block.super }}
<li><a href="{% url 'company_list' %}">{% trans "Companies" %}</a></li>
<li class="active">{{ company.name }}</li>{% endblock %}

{% block content %}


<div class="row">
<div class="col-md-7">
<h1 class="page-header" style="margin-top:0;">{{ company.name }}{% if company.verified %} <small><span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span> verified</small>{% endif %}</h1>
{% thumbnail company.logo "300x300" format="PNG" as im %}
<p><img src="{{ im.url }}"></p>
<hr>
{% endthumbnail %}

<div class="company--description">{{ company.description|safe }}</div>

</div>
<div class="col-md-5">
<table class="table table-hover">
{% with company.get_categories as categories %}
{% if categories %}
<tr>
    <td>{% trans "Categories" %}:</td>
    <td>{{ categories }}</td>
</tr>
{% endif %}{% endwith %}
{% with company.get_scope_of_operation as scopes %}
{% if scopes %}
<tr>
    <td>{% trans "Scope of operation" %}:</td>
    <td>{{ scopes }}</td>
</tr>
{% endif %}{% endwith %}
{% if company.depots > 0 %}
<tr>
    <td>{% trans "Depots" %}:</td>
    <td>{{ company.depots }}</td>
</tr>
{% endif %}
{% if company.employees > 0 %}
<tr>
    <td>{% trans "Employees" %}:</td>
    <td>{{ company.employees }}</td>
</tr>
{% endif %}
</table>

<div id="company-info">
<img src="{% static 'img/loader.gif' %}">
</div>

</div>
</div>

<script type="text/javascript">
$(function () {
    $("#company-info").load("{% url 'company_sidebar' company.slug %}");
});
</script>
{% endblock %}

apps/companies/templates/companies/company_list.html
{% extends "base.html" %}
{% load i18n staticfiles thumbnail %}

{% block title %}{{ block.super }} - {% trans "Companies" %}{% endblock %}

{% block breadcrumb_path %}{{ block.super }}<li class="active">{% trans "Companies" %}</li>{% endblock %}

{% block content %}
<h1 class="page-header">{% trans "Companies" %}</h1>

{% for company in companies %}
<div class="row">
<div class="col-md-8">
    <h3><a href="{% url 'company_details' company.slug %}">{{ company.name }}</a></h3>
    <div class="company--short-description">{{ company.short_description|safe }}</div>
</div>
<div class="col-md-4">
    {% thumbnail company.logo "300x300" format="PNG" as im %}
    <img src="{{ im.url }}">
    {% endthumbnail %}
</div>
</div>
{% endfor %}

{% if is_paginated %}
    <ul class="pagination pagination-centered">
        {% if page_obj.has_previous %}
            <li><a href="?page=1">&laquo;&laquo;</a></li>
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% endif %}

        {% for i in paginator.page_range %}
            <li {% if page_obj.number == i %} class="active" {% endif %}><a href="?page={{i}}">{{i}}</a></li>
        {% endfor %}

        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            <li><a href="?page={{ page_obj.paginator.num_pages }}">&raquo;&raquo;</a></li>
        {% endif %}
    </ul>
{% endif %}

{% endblock %}

apps/companies/templates/companies/company_manage.html
{% extends "base.html" %}
{% load i18n staticfiles thumbnail %}

{% block breadcrumb_path %}{{ block.super }}
<li><a href="{% url 'company_list' %}">{% trans "Companies" %}</a></li>
<li><a href="{{ company.get_absolute_url }}">{{ company.name }}</a></li>
<li class="active">{% trans "Manage" %}</li>{% endblock %}
{% block content %}


<div class="row">
<div class="col-md-8">
<h1 class="page-header" style="margin-top:0;">{{ company.name }}{% if company.verified %} <small><span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span> verified</small>{% endif %}</h1>

{% if company.logo %}
{% thumbnail company.logo "300x300" format="PNG" as im %}
<div>
<img src="{{ im.url }}">
<a class="btn btn-primary btn-xs pull-right" href="{% url 'company_edit_logo' company.slug %}">{% trans "Change logo" %}</a>
<hr>
</div>
{% endthumbnail %}
{% else %}
<div class="alert alert-info">
{% trans "You didn't upload any company logo yet." %}
<a class="btn btn-primary btn-xs pull-right" href="{% url 'company_edit_logo' company.slug %}">{% trans "Upload logo" %}</a>
</div>
{% endif %}

<table class="table table-bordered table-hover">
<tr><td>{% trans "VAT Number" %}</td><td>{{ company.vat }}</td></tr>
<tr><td>{% trans "Business segments" %}</td>
<td>{{ company.get_categories }}
<a href="{% url 'company_edit_business_segments' company.slug %}" class="pull-right" title="{% trans 'Edit' %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a></td></tr>
<tr><td>{% trans "Scope of operation" %}</td>
<td>{{ company.get_scope_of_operation }}
<a href="{% url 'company_edit_scope_of_operation' company.slug %}" class="pull-right" title="{% trans 'Edit' %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a></td></tr>
</table>

<table class="table table-bordered">
<tr>
    <td width="50%">{% trans "Employees" %} 
    <span class="pull-right" style="font-size:32px;">{{ company.employees }}</span></td>
    <td>{% trans "Depots" %} 
    <span class="pull-right" style="font-size:32px;">{{ company.depots }}</span></td>
</tr>
</table>

</div>
<div class="col-md-4">
{% include "companies/_side_toolbar.html" with section="summary" %}
</div>
</div>
{% endblock %}