apps/accounts/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import (
    login,
    logout,
    password_change,
    password_change_done,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
)
from django.views.generic import TemplateView
from .decorators import ajax_required
from .views import (
    profile_view,
    MyProfileUpdateView,
)


urlpatterns = patterns(
    '',
    url(
        r'^login/$', login,
        {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),

    url(
        r'^password-change/$',
        password_change,
        {'template_name': 'accounts/password_change_form.html'},
        name='password_change'),
    url(
        r'^password-change/done/$',
        password_change_done,
        {'template_name': 'accounts/password_change_done.html'},
        name='password_change_done'),
    url(
        r'^password-reset/$',
        password_reset,
        {'template_name': 'accounts/password_reset_form.html'},
        name='password_reset'),
    url(
        r'^password-reset/done/$',
        password_reset_done,
        {'template_name': 'accounts/password_reset_done.html'},
        name='password_reset_done'),
    url(
        r'^password-reset/(?P<uidb64>.+)/(?P<token>.+)/confirm/$',
        password_reset_confirm,
        {'template_name': 'accounts/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(
        r'^password-reset/complete/$',
        password_reset_complete,
        {'template_name': 'accounts/password_reset_complete.html'},
        name='password_reset_complete'),

    url(r'^user-toolbar/$', ajax_required(
        TemplateView.as_view(template_name='accounts/user_toolbar.html'))),
    url(
        r'^edit-profile/$',
        MyProfileUpdateView.as_view(),
        name='edit_my_profile'),
    url(
        r'^profile/$', profile_view,
        name='my_profile'),
)

apps/equipment/urls.py
from django.conf.urls import patterns, url
import mptt_urls
from .views import (
    # ManufacturerListView,
    # ManufacturerDetailView,
    equipment_search_view,
    # category_view,
    equipment_view,
    # equipment_item_view,
)

urlpatterns = patterns(
    '',
    # url(
    #     r'^manufacturers/$',
    #     ManufacturerListView.as_view(),
    #     name='manufacturer_list'),
    # url(
    #     r'^manufacturers/(?P<slug>[-\w]+)/$',
    #     ManufacturerDetailView.as_view(),
    #     name='manufacturer_details'),
    # url(
    #     r'^equipment/(?P<manufacturer_slug>[-\w]+)/(?P<slug>[-\w]+)/(?P<id>\d+)/$',
    #     equipment_item_view,
    #     name='equipment_item_details'),
    url(
        r'^equipment/(?P<category_slug>[-\w]+)/(?P<manufacturer_slug>[-\w\d]+)/(?P<model>[-\w\d]+)/(?P<id>\d+)/$',
        equipment_view,
        name='equipment_details'),
    # url(
    #     r'^categories/(?P<path>[-\w/]*)/$',
    #     mptt_urls.view(
    #         model='apps.equipment.models.EquipmentCategory',
    #         view=category_view,
    #         slug_field='slug'),
    #     name='category_details'),
    # url(
    #     r'^categories/(?P<slug>[-\w]+)/$',
    #     EquipmentCategoryDetailView.as_view(),
    #     name='category_details'),
    url(r'^search/$', equipment_search_view, name='search'),
)

apps/invitation/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required
from .settings import INVITE_ONLY


urlpatterns = patterns(
    '',
    url(r'^invitation/$',
        login_required(TemplateView.as_view(
            template_name='invitation/invitation_home.html')),
        name='invitation_home'),
    url(r'^invitation/invite/$',
        'apps.invitation.views.invite',
        name='invitation_invite'),
    url(r'^invitation/invite/complete/$',
        login_required(TemplateView.as_view(
            template_name='invitation/invitation_complete.html')),
        name='invitation_complete'),
    url(r'^invitation/invite/unavailable/$',
        login_required(TemplateView.as_view(
            template_name='invitation/invitation_unavailable.html')),
        name='invitation_unavailable'),
    url(r'^invitation/accept/complete/$',
        TemplateView.as_view(
            template_name='invitation/invitation_registered.html'),
        name='invitation_registered'),
    url(r'^invitation/accept/(?P<invitation_key>\w+)/$',
        'apps.invitation.views.register',
        name='invitation_register'),
)


if INVITE_ONLY:
    urlpatterns += patterns(
        '',
        url(r'^register/$',
            RedirectView.as_view(
                url='../invitation/invite_only/',
                permanent=False),
            name='registration_register'),
        url(r'^invitation/invite_only/$',
            TemplateView.as_view(
                template_name='invitation/invite_only.html'),
            name='invitation_invite_only'),
        url(r'^invitation/reward/$',
            'apps.invitation.views.reward',
            name='invitation_reward'),
    )

cranelocator/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = patterns(
    '',
    url(r'^$', 'cranelocator.views.home', name='home'),

    url(r'^', include('apps.accounts.urls')),
    url(r'^', include('apps.invitation.urls')),
    url(r'^', include('apps.companies.urls')),
    url(r'^', include('apps.equipment.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),

    url('^robots\.txt$', TemplateView.as_view(
        template_name='robots.txt', content_type='text/plain')),
    url('^humans\.txt$', TemplateView.as_view(
        template_name='humans.txt', content_type='text/plain')),
)


# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/accounts/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)


class CLUserManager(BaseUserManager):
    """
    Creates and saves a User with the given email, full_name and password.
    """
    def _create_user(self, email, full_name, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          full_name=full_name,
                          is_superuser=is_superuser,
                          date_joined=now,
                          last_login=now,
                          **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, full_name, password=None, **extra_fields):
        return self._create_user(
            email, full_name, password,
            False, False, **extra_fields)

    def create_superuser(
            self, email, full_name, password=None, **extra_fields):
        """
        Creates and saves a superuser with the given email,
        full_name and password.
        """
        return self._create_user(
            email, full_name, password,
            True, True, **extra_fields)


class CLUser(AbstractBaseUser, PermissionsMixin):
    """
    A model which implements the authentication model.

    Email, password and full_name are required. Other fields are optional.

    Email field is used for logging in.
    """
    MEASUREMENT_SYSTEM_CHOICES = (
        ('metric', _('Metric')),
        ('imperial', _('Imperial')),
    )

    email = models.EmailField(
        _('Email'), max_length=255, unique=True)
    full_name = models.CharField(_('Full name'), max_length=100)
    measurement_system = models.CharField(
        _('Measurement system'), max_length=20, default='metric',
        choices=MEASUREMENT_SYSTEM_CHOICES,
    )

    is_staff = models.BooleanField(
        _('Staff status'), default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'))
    is_active = models.BooleanField(
        _('Active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))

    date_joined = models.DateTimeField(_('Date joined'), default=timezone.now)

    objects = CLUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    class Meta:
        verbose_name = _(u'User')
        verbose_name_plural = _(u'Users')

    def __str__(self):
        return self.full_name or self.email

    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.full_name

    def can_send_invitations(self):
        return self.groups.filter(name='Can send invitations').exists()

    def is_verified(self):
        return self.groups.filter(name='Verified').exists()

    def get_company_roles(self):
        return self.company_roles.all()

apps/accounts/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    ReadOnlyPasswordHashField,
)
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from .models import CLUser


class CLUserChangeForm(UserChangeForm):
    password = ReadOnlyPasswordHashField(
        label=_('Password'),
        help_text=_(
            u'Raw passwords are not stored, so there is no way to see '
            u'this user\'s password, but you can change the password '
            u'using <a href="password/">this form</a>.'))

    class Meta:
        model = CLUser
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # del self.fields['username']
        # f = self.fields.get('user_permissions', None)
        # if f is not None:
        #     f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        return self.initial['password']


class CLUserCreationForm(UserCreationForm):
    """
    A form that creates a user, with no privileges,
    from the given email, full_name and password.
    """
    error_messages = {
        'duplicate_email': _("A user with that email already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = CLUser
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        del self.fields['username']

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            CLUser.objects.get(email=email)
        except CLUser.DoesNotExist:
            return email
        raise forms.ValidationError(self.error_messages['duplicate_email'])

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class EditCLUserForm(forms.ModelForm):
    class Meta:
        model = CLUser
        fields = ('email', 'full_name', 'measurement_system')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'email',
            'full_name',
            'measurement_system',
            ButtonHolder(
                Submit('submit', _('Save'), css_class='btn btn-primary')
            )
        )


class CLUserRegistrationForm(CLUserCreationForm):
    class Meta:
        model = CLUser
        fields = ('email', 'full_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'email',
            'full_name',
            'password1',
            'password2',
            ButtonHolder(
                Submit('submit', _('Create user'), css_class='btn btn-primary')
            )
        )

apps/accounts/views.py
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, redirect, render
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.views.generic import UpdateView
from django.conf import settings
from django.contrib.messages.views import SuccessMessageMixin
from .forms import EditCLUserForm
from .models import CLUser


@login_required
def profile_view(request):
    return render(
        request,
        'accounts/my_profile.html',
        {
            'user': request.user,
        })


class MyProfileUpdateView(SuccessMessageMixin, UpdateView):
    model = CLUser
    template_name = 'accounts/edit_my_profile.html'
    form_class = EditCLUserForm
    success_message = _(u"Your profile settings was changed.")

    def get_object(self):
        return CLUser.objects.get(pk=self.request.user.pk)

    def get_success_url(self):
        return reverse(
            'cluser_details', args=(self.request.user.pk,))

apps/accounts/templates/accounts/_load_user_toolbar.html
<script>
    $(document).ready(function () {
        $('.__slot--user-bar').load('/user-toolbar/');
    });
</script>

apps/accounts/templates/accounts/edit_my_profile.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Edit account" %}{% endblock %}

{% block head_tail %}{{ form.media }}{% endblock %}

{% block breadcrumb_path %}
{{ block.super }}
<li><a href="{% url 'my_profile' %}">{% trans "Your profile" %}</a></li>
<li class="active">{% trans "Edit" %}</li>
{% endblock %}

{% block content %}
<h2>{% trans "Edit profile" %}</h2>

{% crispy form %}
{% endblock %}

apps/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load i18n staticfiles crispy_forms_tags %}
{% block breadcrumb_path %}{{ block.super }}<li class="active">{% trans "Login" %}</li>{% endblock %}
{% block content %}
<h2>{% trans "Login" %}</h2>

<form class="form-vertical" role="form" method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}

{{ form|crispy }}

<input type="hidden" name="next" value="{{ next }}" />
<button class="btn btn-primary" type="submit">{% trans "Login" %}</button>
<a href="{% url 'password_reset' %}" class="btn btn-link">{% trans "Forgot the password?" %}</a>
</form>
{% endblock %}

apps/accounts/templates/accounts/my_profile.html
{% extends "base.html" %}
{% load i18n staticfiles %}

{% block title %}{{ block.super }} - {% trans "Profile" %}{% endblock %}

{% block breadcrumb_path %}{{ block.super }}<li class="active">{% trans "Your profile" %}</li>{% endblock %}

{% block content %}
<div class="btn-toolbar pull-right">
<a href="{% url 'edit_my_profile' %}" class="btn btn-success">
<span class="glyphicon glyphicon-edit"></span> {% trans "Edit profile" %}</a>

{% if user.can_send_invitations %}
<a href="{% url 'invitation_invite' %}" class="btn btn-default"><span class="glyphicon glyphicon-send"></span> {% trans "Send invite" %}</a>
{% endif %}
</div>

<h1>{{ user.get_full_name }}{% if user.is_verified %} <small><span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span> verified</small>{% endif %}</h1>
<br>
<dl>
    <dt>{% trans "Email" %}</dt>
    <dd>{{ user.email }}</dd>
    <dt>{% trans "Measurement system" %}</dt>
    <dd>{{ user.get_measurement_system_display }}</dd></dl>
<hr>
<div class="btn-toolbar">
<a href="{% url 'password_change' %}" class="btn btn-default">{% trans "Change your password" %}</a>
</div>

{% with user as cluser %}
{% include "companies/_company_roles_for_cluser.html" %}
{% endwith %}
<div class="btn-toolbar">
<a href="{% url 'company_add' %}" class="btn btn-default">
<span class="glyphicon glyphicon-plus"></span> {% trans "Create company" %}</a>
</div>

{% endblock %}

apps/accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Password changed successfully" %}{% endblock %}

{% block head_tail %}{{ form.media }}{% endblock %}

{% block breadcrumb_path %}
{{ block.super }}
<li><a href="{% url 'my_profile' %}">{% trans "Your profile" %}</a></li>
<li class="active">{% trans "Password changed successfully" %}</li>
{% endblock %}

{% block content %}
<h2>{% trans "Password changed successfully" %}</h2>

<p>{% trans "Your password was changed." %}</p>
{% endblock %}

apps/accounts/templates/accounts/password_change_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Change password" %}{% endblock %}

{% block head_tail %}{{ form.media }}{% endblock %}

{% block breadcrumb_path %}
{{ block.super }}
<li><a href="{% url 'my_profile' %}">{% trans "Your profile" %}</a></li>
<li class="active">{% trans "Change password" %}</li>
{% endblock %}

{% block content %}
<h2>{% trans "Change password" %}</h2>

<form class="form-vertical" role="form" method="post">
{% csrf_token %}

{{ form|crispy }}

<button class="btn btn-primary" type="submit">{% trans "Save" %}</button>
</form>
{% endblock %}

apps/accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Password reset complete" %}{% endblock %}

{% block head_tail %}{{ form.media }}{% endblock %}

{% block breadcrumb_path %}
{{ block.super }}
<li class="active">{% trans "Password reset complete" %}</li>
{% endblock %}

{% block content %}
<h2>{% trans "Password reset complete" %}</h2>

<p>{% trans "Your password was changed. Now you can login with new password." %}</p>

<p><a href="{% url 'login' %}" class="btn btn-default">{% trans "Login" %}</a></p>
{% endblock %}

apps/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Password reset" %}{% endblock %}

{% block head_tail %}{{ form.media }}{% endblock %}

{% block breadcrumb_path %}
{{ block.super }}
<li class="active">{% trans "Password reset" %}</li>
{% endblock %}

{% block content %}
<h2>{% trans "Password reset" %}</h2>

<form class="form-vertical" role="form" method="post">
{% csrf_token %}

{{ form|crispy }}

<button class="btn btn-primary" type="submit">{% trans "Reset password" %}</button>
</form>
{% endblock %}

apps/accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Check your email" %}{% endblock %}

{% block head_tail %}{{ form.media }}{% endblock %}

{% block breadcrumb_path %}
{{ block.super }}
<li class="active">{% trans "Check your email" %}</li>
{% endblock %}

{% block content %}
<h2>{% trans "Check your email" %}</h2>

<p>{% trans "Wait a minute and check your email inbox. You should get email with a special link for reset the password. Follow the instructions there." %}</p>
{% endblock %}

apps/accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {% trans "Password reset" %}{% endblock %}

{% block head_tail %}{{ form.media }}{% endblock %}

{% block breadcrumb_path %}
{{ block.super }}
<li class="active">{% trans "Password reset" %}</li>
{% endblock %}

{% block content %}
<h2>{% trans "Password reset" %}</h2>

<form class="form-vertical" role="form" method="post">
{% csrf_token %}

{{ form|crispy }}

<button class="btn btn-primary" type="submit">{% trans "Reset password" %}</button>
</form>
{% endblock %}

apps/accounts/templates/accounts/registration_form.html
{% extends "base.html" %}
{% load i18n staticfiles crispy_forms_tags %}
{% block breadcrumb_path %}{{ block.super }}<li class="active">{% trans "Registration" %}</li>{% endblock %}
{% block content %}
<h2>{% trans "Registration" %}</h2>

{% crispy form %}

{% endblock %}

apps/accounts/templates/accounts/user_toolbar.html
{% load i18n %}
{% if user.is_authenticated %}
<li><a href="{% url 'my_profile' %}" rel="nofollow">{% trans "Your profile" %}</a></li>
<li><a href="{% url 'logout' %}" rel="nofollow">{% trans "Logout" %}</a></li>
{% else %}
<li><a href="{% url 'login' %}" rel="nofollow">{% trans "Login" %}</a></li>
{% endif %}